# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c99a820a8463bb3dcb7ff134250911db4dcad3f7ba87aea1034527c87b2cf02091a6e70d41f2a15fdc3f32c5b13c0da2d816dc3572c077b056c1b6b01fed1f6

test:
  secret_key_base: 1d00375f036626c276883a9c47b97604a1037864877933fee1c5fa397d8bcc61cdc8d752f5159b542dd439586018c72d1f827a648f26418748ec0ebd295d27ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
